# ruff: noqa: E501, F401, F403, I001
from __future__ import annotations

from app.core.config import get_settings
import app.services.evidence_audit_views as _evidence_audit_views
import app.services.evidence_claim_feedback as _evidence_claim_feedback
import app.services.evidence_claim_support_impacts as _evidence_claim_support_impacts
import app.services.evidence_claim_support_replay_alerts as _evidence_claim_support_replay_alerts
import app.services.evidence_common as _evidence_common
import app.services.evidence_manifests as _evidence_manifests
import app.services.evidence_provenance as _evidence_provenance
import app.services.evidence_provenance_exports as _evidence_provenance_exports
import app.services.evidence_records as _evidence_records
import app.services.evidence_release_readiness as _evidence_release_readiness
import app.services.evidence_semantic_trace as _evidence_semantic_trace
import app.services.evidence_technical_report_exports as _evidence_technical_report_exports
from app.services.evidence_audit_views import *
from app.services.evidence_claim_feedback import *
from app.services.evidence_constants import *
from app.services.evidence_manifests import *
from app.services.evidence_operator_runs import record_knowledge_operator_run
from app.services.evidence_provenance_exports import *
from app.services.evidence_search_closure import technical_report_search_evidence_closure_payload
from app.services.evidence_search_packages import *
from app.services.evidence_technical_report_exports import *

payload_sha256 = _evidence_common.payload_sha256
PROV_EXPORT_RECEIPT_SIGNATURE_ALGORITHM = _evidence_provenance.PROV_EXPORT_RECEIPT_SIGNATURE_ALGORITHM
TECHNICAL_REPORT_PROV_EXPORT_ARTIFACT_KIND = _evidence_provenance.TECHNICAL_REPORT_PROV_EXPORT_ARTIFACT_KIND
TECHNICAL_REPORT_PROV_EXPORT_FILENAME = _evidence_provenance.TECHNICAL_REPORT_PROV_EXPORT_FILENAME
TECHNICAL_REPORT_PROV_EXPORT_RECEIPT_SCHEMA = _evidence_provenance.TECHNICAL_REPORT_PROV_EXPORT_RECEIPT_SCHEMA
_PROV_INTEGRITY_EXCLUDED_FIELDS = _evidence_provenance.PROV_INTEGRITY_EXCLUDED_FIELDS
_prov_activity = _evidence_provenance.add_prov_activity
_prov_entity = _evidence_provenance.add_prov_entity
_prov_relation = _evidence_provenance.add_prov_relation
_frozen_export_receipt = _evidence_provenance.frozen_export_receipt
_frozen_export_sha256 = _evidence_provenance.frozen_export_sha256
_prov_missing_relation_references = _evidence_provenance.missing_relation_references
_prov_export_integrity_payload = _evidence_provenance.prov_export_integrity_payload
_prov_identifier = _evidence_provenance.prov_identifier
_receipt_hash_basis = _evidence_provenance.receipt_hash_basis
_receipt_hash_chain_sha256 = _evidence_provenance.receipt_hash_chain_sha256
_late_interaction_matches = _evidence_records.late_interaction_matches
_operator_run_payload = _evidence_records.operator_run_payload
_result_payload = _evidence_records.result_payload
_select_by_ids = _evidence_records.select_by_ids
_source_evidence_payloads = _evidence_records.source_evidence_payloads
_uuid_values = _evidence_common.uuid_values
_string_values = _evidence_common.string_values
_source_record_key = _evidence_common.source_record_key
_claim_derivation_payload = _evidence_technical_report_exports.claim_derivation_payload
_claim_derivation_provenance_lock_contract_mismatches = _evidence_technical_report_exports.claim_derivation_provenance_lock_contract_mismatches
_claim_derivation_support_judgment_contract_mismatches = _evidence_technical_report_exports.claim_derivation_support_judgment_contract_mismatches
_evidence_card_snapshot = _evidence_technical_report_exports.evidence_card_snapshot
_latest_passed_release_bindings_by_request = _evidence_technical_report_exports.latest_passed_release_bindings_by_request
_claim_retrieval_feedback_payload = _evidence_claim_feedback.claim_retrieval_feedback_payload
_claim_retrieval_feedback_rows_for_verification_task = _evidence_claim_feedback.claim_retrieval_feedback_rows_for_verification_task
_set_claim_feedback_append_only_link = _evidence_claim_feedback.set_claim_feedback_append_only_link
_technical_report_claim_feedback_integrity_payload = _evidence_claim_feedback.technical_report_claim_feedback_integrity_payload
_technical_report_claim_feedback_payloads = _evidence_claim_feedback.technical_report_claim_feedback_payloads
_technical_report_claim_feedback_row_integrity = _evidence_claim_feedback.technical_report_claim_feedback_row_integrity
_technical_report_claim_feedback_status = _evidence_claim_feedback.technical_report_claim_feedback_status
_context_pack_audit_refs = _evidence_release_readiness.context_pack_audit_refs
_context_pack_sha256s_from_artifacts = _evidence_release_readiness.context_pack_sha256s_from_artifacts
_release_readiness_audit_summary = _evidence_release_readiness.release_readiness_audit_summary
_release_readiness_db_gate_payload = _evidence_release_readiness.release_readiness_db_gate_payload
_release_readiness_db_gate_trace_ref = _evidence_release_readiness.release_readiness_db_gate_trace_ref
_release_readiness_ref_key = _evidence_release_readiness.release_readiness_ref_key
_release_readiness_refs_from_context_pack_artifacts = _evidence_release_readiness.release_readiness_refs_from_context_pack_artifacts
_source_search_request_ids_from_context_pack_artifacts = _evidence_release_readiness.source_search_request_ids_from_context_pack_artifacts
_technical_report_readiness_db_gate_for_verification_task = _evidence_release_readiness.technical_report_readiness_db_gate_for_verification_task
_technical_report_release_readiness_db_gate_record_payload = _evidence_release_readiness.technical_report_release_readiness_db_gate_record_payload
_technical_report_release_readiness_db_gate_row_integrity = _evidence_release_readiness.technical_report_release_readiness_db_gate_row_integrity
_verification_check = _evidence_release_readiness.verification_check
_verification_check_passed = _evidence_release_readiness.verification_check_passed
_with_release_readiness_db_gate_record = _evidence_release_readiness.with_release_readiness_db_gate_record
_claim_support_replay_alert_fixture_corpus_snapshots_by_promotion_event = _evidence_claim_support_replay_alerts.claim_support_replay_alert_fixture_corpus_snapshots_by_promotion_event
_claim_support_replay_alert_waiver_closure_events_by_impact = _evidence_claim_support_replay_alerts.claim_support_replay_alert_waiver_closure_events_by_impact
_claim_support_replay_alert_waiver_lifecycle_summary = _evidence_claim_support_replay_alerts.claim_support_replay_alert_waiver_lifecycle_summary
_replay_alert_fixture_corpus_row_payload = _evidence_claim_support_replay_alerts.replay_alert_fixture_corpus_row_payload
_replay_alert_fixture_corpus_snapshot_governance_integrity = _evidence_claim_support_replay_alerts.replay_alert_fixture_corpus_snapshot_governance_integrity
_replay_alert_fixture_corpus_snapshot_payload = _evidence_claim_support_replay_alerts.replay_alert_fixture_corpus_snapshot_payload
_waiver_closure_event_integrity = _evidence_claim_support_replay_alerts.waiver_closure_event_integrity
_waiver_closure_event_payload = _evidence_claim_support_replay_alerts.waiver_closure_event_payload
_change_impact_payload = _evidence_claim_support_impacts.change_impact_payload
_claim_support_policy_change_impact_events_by_row = _evidence_claim_support_impacts.claim_support_policy_change_impact_events_by_row
_fixture_promotion_event_payload = _evidence_claim_support_impacts.fixture_promotion_event_payload
_claim_support_policy_change_impact_refs = _evidence_claim_support_impacts.claim_support_policy_change_impact_refs
_claim_support_policy_change_impact_summary = _evidence_claim_support_impacts.claim_support_policy_change_impact_summary
_claim_support_policy_fixture_promotion_events_by_impact = _evidence_claim_support_impacts.claim_support_policy_fixture_promotion_events_by_impact
_empty_claim_support_policy_change_impact_summary = _evidence_claim_support_impacts.empty_claim_support_policy_change_impact_summary
_report_evidence_card_source_records = _evidence_semantic_trace.report_evidence_card_source_records
_semantic_trace_payload = _evidence_semantic_trace.semantic_trace_payload
_source_record_payloads_from_semantic_trace = _evidence_semantic_trace.source_record_payloads_from_semantic_trace
_technical_report_integrity_payload = _evidence_semantic_trace.technical_report_integrity_payload
_technical_report_provenance_edges = _evidence_semantic_trace.technical_report_provenance_edges
_ensure_evidence_trace_graph = _evidence_manifests.ensure_evidence_trace_graph
_existing_evidence_manifest = _evidence_manifests.existing_evidence_manifest
_evidence_manifest_has_release_readiness_db_gate_record = _evidence_manifests.evidence_manifest_has_release_readiness_db_gate_record
_evidence_manifest_integrity_payload = _evidence_manifests.evidence_manifest_integrity_payload
_evidence_manifest_matches_current_payload = _evidence_manifests.evidence_manifest_matches_current_payload
_evidence_manifest_response = _evidence_manifests.evidence_manifest_response
_evidence_manifest_row_from_payload = _evidence_manifests.evidence_manifest_row_from_payload
_update_evidence_manifest_row_from_payload = _evidence_manifests.update_evidence_manifest_row_from_payload
_provenance_export_receipt_payload = _evidence_audit_views.provenance_export_receipt_payload
_build_agent_task_provenance_export = _evidence_provenance_exports._build_agent_task_provenance_export
_existing_prov_export_artifact = _evidence_provenance_exports._existing_prov_export_artifact
_record_prov_export_supersession_attempt = _evidence_provenance_exports._record_prov_export_supersession_attempt
_technical_report_change_impact_for_governance = _evidence_provenance_exports._technical_report_change_impact_for_governance


def _prov_export_receipt_signature(receipt_sha256: str) -> dict[str, object]:
    return _evidence_provenance.prov_export_receipt_signature(receipt_sha256, settings_provider=get_settings)


def _prov_export_receipt(prov_export: dict[str, object], **kwargs) -> dict[str, object]:
    return _evidence_provenance.prov_export_receipt(prov_export, settings_provider=get_settings, **kwargs)


def _frozen_prov_export_payload(prov_export: dict[str, object], **kwargs) -> dict[str, object]:
    return _evidence_provenance.frozen_prov_export_payload(prov_export, settings_provider=get_settings, **kwargs)


def _prov_export_receipt_integrity(payload: dict[str, object] | None) -> dict[str, object]:
    return _evidence_provenance.prov_export_receipt_integrity(payload, settings_provider=get_settings)


_EVIDENCE_RECORD_COMPAT_ALIASES = (
    _late_interaction_matches,
    _operator_run_payload,
    _result_payload,
    _source_evidence_payloads,
)
_EVIDENCE_PROVENANCE_COMPAT_ALIASES = (
    PROV_EXPORT_RECEIPT_SIGNATURE_ALGORITHM,
    TECHNICAL_REPORT_PROV_EXPORT_RECEIPT_SCHEMA,
    _PROV_INTEGRITY_EXCLUDED_FIELDS,
    _prov_missing_relation_references,
    _receipt_hash_basis,
    _receipt_hash_chain_sha256,
)
