from __future__ import annotations

# Compatibility facade for the improvement-case family after the self-hosting split.
from app.services.improvement_case_models import (
    CONVERTED_IMPROVEMENT_STATUSES,
    DEFAULT_IMPROVEMENT_CASES_PATH,
    DEPLOYED_IMPROVEMENT_STATUSES,
    IMPROVEMENT_ARTIFACT_TYPES,
    IMPROVEMENT_CASE_SCHEMA_NAME,
    IMPROVEMENT_CASE_SCHEMA_VERSION,
    IMPROVEMENT_CASE_STATUSES,
    IMPROVEMENT_CAUSE_CLASSES,
    IMPROVEMENT_SOURCE_TYPES,
    MEASURED_IMPROVEMENT_STATUSES,
    VERIFIED_IMPROVEMENT_STATUSES,
    ImprovementCase,
    ImprovementCaseArtifact,
    ImprovementCaseContractIssue,
    ImprovementCaseDeployment,
    ImprovementCaseMeasurement,
    ImprovementCaseObservation,
    ImprovementCaseRegistry,
    ImprovementCaseSource,
    ImprovementCaseVerification,
)
from app.services.improvement_case_observations import (
    collect_eval_failure_case_observations,
    collect_failed_agent_task_observations,
    collect_failed_agent_verification_observations,
    collect_hygiene_finding_observations,
    import_improvement_case_observations,
)
from app.services.improvement_case_registry import (
    build_improvement_case_manifest,
    empty_improvement_case_registry,
    filter_improvement_cases,
    load_improvement_case_registry,
    load_improvement_case_registry_for_validation,
    record_improvement_case,
    resolve_improvement_cases_path,
    summarize_improvement_cases,
    validate_improvement_case_registry,
    write_improvement_case_registry,
)

__all__ = [
    "CONVERTED_IMPROVEMENT_STATUSES",
    "DEFAULT_IMPROVEMENT_CASES_PATH",
    "DEPLOYED_IMPROVEMENT_STATUSES",
    "IMPROVEMENT_ARTIFACT_TYPES",
    "IMPROVEMENT_CASE_SCHEMA_NAME",
    "IMPROVEMENT_CASE_SCHEMA_VERSION",
    "IMPROVEMENT_CASE_STATUSES",
    "IMPROVEMENT_CAUSE_CLASSES",
    "IMPROVEMENT_SOURCE_TYPES",
    "MEASURED_IMPROVEMENT_STATUSES",
    "VERIFIED_IMPROVEMENT_STATUSES",
    "ImprovementCase",
    "ImprovementCaseArtifact",
    "ImprovementCaseContractIssue",
    "ImprovementCaseDeployment",
    "ImprovementCaseMeasurement",
    "ImprovementCaseObservation",
    "ImprovementCaseRegistry",
    "ImprovementCaseSource",
    "ImprovementCaseVerification",
    "build_improvement_case_manifest",
    "collect_eval_failure_case_observations",
    "collect_failed_agent_task_observations",
    "collect_failed_agent_verification_observations",
    "collect_hygiene_finding_observations",
    "empty_improvement_case_registry",
    "filter_improvement_cases",
    "import_improvement_case_observations",
    "load_improvement_case_registry",
    "load_improvement_case_registry_for_validation",
    "record_improvement_case",
    "resolve_improvement_cases_path",
    "summarize_improvement_cases",
    "validate_improvement_case_registry",
    "write_improvement_case_registry",
]
