from __future__ import annotations

import app.services.semantic_registry_contracts as _contracts
import app.services.semantic_registry_state as _state
import app.services.semantic_registry_storage as _storage

SemanticRegistry = _contracts.SemanticRegistry
SemanticRegistryCategoryDefinition = _contracts.SemanticRegistryCategoryDefinition
SemanticRegistryConceptDefinition = _contracts.SemanticRegistryConceptDefinition
SemanticRegistryEntityTypeDefinition = _contracts.SemanticRegistryEntityTypeDefinition
SemanticRegistryRelationDefinition = _contracts.SemanticRegistryRelationDefinition
SemanticRegistryTermDefinition = _contracts.SemanticRegistryTermDefinition
metadata_without = _contracts.metadata_without
normalize_semantic_text = _contracts.normalize_semantic_text
semantic_registry_from_payload = _contracts.semantic_registry_from_payload

WORKSPACE_SEMANTIC_STATE_KEY = _state.WORKSPACE_SEMANTIC_STATE_KEY
canonicalize_semantic_relation_endpoints = _state.canonicalize_semantic_relation_endpoints
ensure_workspace_semantic_registry = _state.ensure_workspace_semantic_registry
get_active_semantic_ontology_snapshot = _state.get_active_semantic_ontology_snapshot
get_semantic_registry = _state.get_semantic_registry
get_semantic_relation_definition = _state.get_semantic_relation_definition
infer_semantic_entity_type = _state.infer_semantic_entity_type
persist_semantic_ontology_snapshot = _state.persist_semantic_ontology_snapshot
semantic_entity_types_by_name = _state.semantic_entity_types_by_name
semantic_relations_by_key = _state.semantic_relations_by_key
validate_semantic_relation_instance = _state.validate_semantic_relation_instance

clear_semantic_registry_cache = _storage.clear_semantic_registry_cache
load_semantic_registry_payload = _storage.load_semantic_registry_payload
write_semantic_registry_payload = _storage.write_semantic_registry_payload
