from __future__ import annotations

from fastapi import APIRouter, Depends

import app.api.capabilities as api_capabilities
import app.api.deps as api_deps
from app.api.deps import require_api_capability
from app.api.routers import (
    agent_task_analytics,
    agent_task_artifacts,
    agent_task_lifecycle,
    claim_support_policy_impacts,
)
from app.schemas.agent_task_core import AgentTaskActionDefinitionResponse
from app.services.capabilities import agent_orchestration

router = APIRouter()
router.include_router(agent_task_analytics.router)
router.include_router(agent_task_artifacts.router)
router.include_router(claim_support_policy_impacts.router)

get_storage_service = api_deps.get_storage_service
list_agent_task_action_definitions = agent_orchestration.list_agent_task_action_definitions
list_agent_tasks = agent_task_lifecycle.list_agent_tasks
create_agent_task = agent_task_lifecycle.create_agent_task
get_agent_task_detail = agent_task_lifecycle.get_agent_task_detail
list_agent_task_outcomes = agent_task_lifecycle.list_agent_task_outcomes
create_agent_task_outcome = agent_task_lifecycle.create_agent_task_outcome
get_agent_task_verifications = agent_task_lifecycle.get_agent_task_verifications
approve_agent_task = agent_task_lifecycle.approve_agent_task
reject_agent_task = agent_task_lifecycle.reject_agent_task
get_agent_task_context = agent_task_artifacts.get_agent_task_context
get_agent_task_audit_bundle = agent_task_artifacts.get_agent_task_audit_bundle
get_agent_task_evidence_manifest = agent_task_artifacts.get_agent_task_evidence_manifest
get_agent_task_evidence_trace = agent_task_artifacts.get_agent_task_evidence_trace
get_agent_task_provenance_export = agent_task_artifacts.get_agent_task_provenance_export
list_agent_task_artifacts = agent_task_artifacts.list_agent_task_artifacts
get_agent_task_artifact = agent_task_artifacts.get_agent_task_artifact
get_agent_task_analytics_summary = agent_task_analytics.get_agent_task_analytics_summary
get_agent_task_trends = agent_task_analytics.get_agent_task_trends
get_agent_verification_trends = agent_task_analytics.get_agent_verification_trends
get_agent_approval_trends = agent_task_analytics.get_agent_approval_trends
get_agent_task_recommendation_summary = agent_task_analytics.get_agent_task_recommendation_summary
get_agent_task_recommendation_trends = agent_task_analytics.get_agent_task_recommendation_trends
get_agent_task_cost_summary = agent_task_analytics.get_agent_task_cost_summary
get_agent_task_cost_trends = agent_task_analytics.get_agent_task_cost_trends
get_agent_task_performance_summary = agent_task_analytics.get_agent_task_performance_summary
get_agent_task_performance_trends = agent_task_analytics.get_agent_task_performance_trends
get_agent_task_value_density = agent_task_analytics.get_agent_task_value_density
get_agent_task_decision_signals = agent_task_analytics.get_agent_task_decision_signals
list_agent_task_workflow_summaries = agent_task_analytics.list_agent_task_workflow_summaries
export_agent_task_traces = agent_task_analytics.export_agent_task_traces
claim_support_policy_change_impact_alerts = (
    claim_support_policy_impacts.claim_support_policy_change_impact_alerts
)
claim_support_policy_change_impact_fixture_candidates = (
    claim_support_policy_impacts.claim_support_policy_change_impact_fixture_candidates
)
claim_support_policy_change_impact_worklist = (
    claim_support_policy_impacts.claim_support_policy_change_impact_worklist
)
get_claim_support_policy_change_impact = (
    claim_support_policy_impacts.get_claim_support_policy_change_impact
)
list_claim_support_policy_change_impacts = (
    claim_support_policy_impacts.list_claim_support_policy_change_impacts
)
promote_claim_support_policy_change_impact_fixture_candidates = (
    claim_support_policy_impacts.promote_claim_support_policy_change_impact_fixture_candidates
)
queue_claim_support_policy_change_impact_replay_tasks = (
    claim_support_policy_impacts.queue_claim_support_policy_change_impact_replay_tasks
)
record_claim_support_policy_change_impact_alert_escalations = (
    claim_support_policy_impacts.record_claim_support_policy_change_impact_alert_escalations
)
refresh_claim_support_policy_change_impact_replay_status = (
    claim_support_policy_impacts.refresh_claim_support_policy_change_impact_replay_status
)
summarize_claim_support_policy_change_impacts = (
    claim_support_policy_impacts.summarize_claim_support_policy_change_impacts
)


@router.get(
    "/agent-tasks/actions",
    response_model=list[AgentTaskActionDefinitionResponse],
    dependencies=[Depends(require_api_capability(api_capabilities.AGENT_TASKS_READ))],
)
def read_agent_task_actions() -> list[AgentTaskActionDefinitionResponse]:
    return list_agent_task_action_definitions()


router.include_router(agent_task_lifecycle.router)
