from __future__ import annotations

import importlib as _importlib

from app.db._model_enums import AgentTaskAttemptStatus as AgentTaskAttemptStatus
from app.db._model_enums import AgentTaskDependencyKind as AgentTaskDependencyKind
from app.db._model_enums import AgentTaskOutcomeLabel as AgentTaskOutcomeLabel
from app.db._model_enums import AgentTaskSideEffectLevel as AgentTaskSideEffectLevel
from app.db._model_enums import AgentTaskStatus as AgentTaskStatus
from app.db._model_enums import AgentTaskVerificationOutcome as AgentTaskVerificationOutcome
from app.db._model_enums import KnowledgeOperatorKind as KnowledgeOperatorKind
from app.db._model_enums import KnowledgeOperatorStatus as KnowledgeOperatorStatus
from app.db._model_enums import RetrievalHardNegativeKind as RetrievalHardNegativeKind
from app.db._model_enums import RetrievalJudgmentKind as RetrievalJudgmentKind
from app.db._model_enums import RetrievalLearningCandidateStatus as RetrievalLearningCandidateStatus
from app.db._model_enums import RetrievalTrainingRunStatus as RetrievalTrainingRunStatus
from app.db._model_enums import RunStatus as RunStatus
from app.db._model_enums import SemanticAssertionKind as SemanticAssertionKind
from app.db._model_enums import SemanticBindingOrigin as SemanticBindingOrigin
from app.db._model_enums import SemanticCategoryBindingType as SemanticCategoryBindingType
from app.db._model_enums import SemanticContextScope as SemanticContextScope
from app.db._model_enums import SemanticEntityType as SemanticEntityType
from app.db._model_enums import SemanticEpistemicStatus as SemanticEpistemicStatus
from app.db._model_enums import SemanticEvaluationStatus as SemanticEvaluationStatus
from app.db._model_enums import SemanticEvidenceSourceType as SemanticEvidenceSourceType
from app.db._model_enums import SemanticGovernanceEventKind as SemanticGovernanceEventKind
from app.db._model_enums import SemanticGraphSourceKind as SemanticGraphSourceKind
from app.db._model_enums import SemanticOntologySourceKind as SemanticOntologySourceKind
from app.db._model_enums import SemanticPassStatus as SemanticPassStatus
from app.db._model_enums import SemanticReviewStatus as SemanticReviewStatus
from app.db._model_enums import SemanticTermKind as SemanticTermKind
from app.db._model_enums import (
    TechnicalReportClaimRetrievalFeedbackStatus as TechnicalReportClaimRetrievalFeedbackStatus,
)
from app.db._model_enums import (
    TechnicalReportClaimRetrievalLearningLabel as TechnicalReportClaimRetrievalLearningLabel,
)
from app.db.model_domains import agent_tasks as _agent_tasks_domain
from app.db.model_domains import claim_support as _claim_support_domain
from app.db.model_domains import evaluation_feedback as _evaluation_feedback_domain
from app.db.model_domains import retrieval_interactions as _retrieval_interactions_domain
from app.db.model_domains import (
    retrieval_learning_artifacts as _retrieval_learning_artifacts_domain,
)
from app.db.model_domains import (
    retrieval_learning_examples as _retrieval_learning_examples_domain,
)
from app.db.model_domains import (
    retrieval_replay_governance as _retrieval_replay_governance_domain,
)
from app.db.model_domains.document_artifacts import DocumentChunk as DocumentChunk
from app.db.model_domains.document_artifacts import DocumentFigure as DocumentFigure
from app.db.model_domains.document_artifacts import DocumentRunEvaluation as DocumentRunEvaluation
from app.db.model_domains.document_artifacts import (
    DocumentRunEvaluationQuery as DocumentRunEvaluationQuery,
)
from app.db.model_domains.document_artifacts import DocumentTable as DocumentTable
from app.db.model_domains.document_artifacts import DocumentTableSegment as DocumentTableSegment
from app.db.model_domains.ingest import (
    DOCUMENT_METADATA_NORMALIZE_SQL as DOCUMENT_METADATA_NORMALIZE_SQL,
)
from app.db.model_domains.ingest import (
    DOCUMENT_METADATA_TEXTSEARCH_SQL as DOCUMENT_METADATA_TEXTSEARCH_SQL,
)
from app.db.model_domains.ingest import Document as Document
from app.db.model_domains.ingest import DocumentRun as DocumentRun
from app.db.model_domains.ingest import IngestBatch as IngestBatch
from app.db.model_domains.ingest import IngestBatchItem as IngestBatchItem
from app.db.model_domains.platform import ApiIdempotencyKey as ApiIdempotencyKey

# Delay these imports until their FK target tables are registered.
_audit_and_evidence_domain = _importlib.import_module("app.db.model_domains.audit_and_evidence")
_semantic_memory_domain = _importlib.import_module("app.db.model_domains.semantic_memory")

AgentTask = _agent_tasks_domain.AgentTask
AgentTaskArtifact = _agent_tasks_domain.AgentTaskArtifact
AgentTaskArtifactImmutabilityEvent = _agent_tasks_domain.AgentTaskArtifactImmutabilityEvent
AgentTaskAttempt = _agent_tasks_domain.AgentTaskAttempt
AgentTaskDependency = _agent_tasks_domain.AgentTaskDependency
AgentTaskOutcome = _agent_tasks_domain.AgentTaskOutcome
AgentTaskVerification = _agent_tasks_domain.AgentTaskVerification
AuditBundleExport = _audit_and_evidence_domain.AuditBundleExport
AuditBundleValidationReceipt = _audit_and_evidence_domain.AuditBundleValidationReceipt
ClaimEvidenceDerivation = _audit_and_evidence_domain.ClaimEvidenceDerivation
ClaimSupportCalibrationPolicy = _claim_support_domain.ClaimSupportCalibrationPolicy
ClaimSupportEvaluation = _claim_support_domain.ClaimSupportEvaluation
ClaimSupportEvaluationCase = _claim_support_domain.ClaimSupportEvaluationCase
ClaimSupportFixtureSet = _claim_support_domain.ClaimSupportFixtureSet
ClaimSupportPolicyChangeImpact = _claim_support_domain.ClaimSupportPolicyChangeImpact
ClaimSupportReplayAlertFixtureCorpusRow = (
    _claim_support_domain.ClaimSupportReplayAlertFixtureCorpusRow
)
ClaimSupportReplayAlertFixtureCorpusSnapshot = (
    _claim_support_domain.ClaimSupportReplayAlertFixtureCorpusSnapshot
)
ClaimSupportReplayAlertFixtureCoverageWaiverEscalation = (
    _claim_support_domain.ClaimSupportReplayAlertFixtureCoverageWaiverEscalation
)
ClaimSupportReplayAlertFixtureCoverageWaiverLedger = (
    _claim_support_domain.ClaimSupportReplayAlertFixtureCoverageWaiverLedger
)
ChatAnswerFeedback = _retrieval_interactions_domain.ChatAnswerFeedback
ChatAnswerRecord = _retrieval_interactions_domain.ChatAnswerRecord
DocumentRunSemanticPass = _semantic_memory_domain.DocumentRunSemanticPass
DocumentSemanticCategoryReview = _semantic_memory_domain.DocumentSemanticCategoryReview
DocumentSemanticConceptReview = _semantic_memory_domain.DocumentSemanticConceptReview
EvidenceManifest = _audit_and_evidence_domain.EvidenceManifest
EvidencePackageExport = _audit_and_evidence_domain.EvidencePackageExport
EvidenceTraceEdge = _audit_and_evidence_domain.EvidenceTraceEdge
EvidenceTraceNode = _audit_and_evidence_domain.EvidenceTraceNode
EvalFailureCase = _evaluation_feedback_domain.EvalFailureCase
EvalObservation = _evaluation_feedback_domain.EvalObservation
KnowledgeOperatorInput = _agent_tasks_domain.KnowledgeOperatorInput
KnowledgeOperatorOutput = _agent_tasks_domain.KnowledgeOperatorOutput
KnowledgeOperatorRun = _agent_tasks_domain.KnowledgeOperatorRun
RetrievalEvidenceSpan = _retrieval_interactions_domain.RetrievalEvidenceSpan
RetrievalEvidenceSpanMultiVector = _retrieval_interactions_domain.RetrievalEvidenceSpanMultiVector
RetrievalHardNegative = _retrieval_learning_examples_domain.RetrievalHardNegative
RetrievalJudgment = _retrieval_learning_examples_domain.RetrievalJudgment
RetrievalJudgmentSet = _retrieval_learning_examples_domain.RetrievalJudgmentSet
RetrievalLearningCandidateEvaluation = (
    _retrieval_learning_artifacts_domain.RetrievalLearningCandidateEvaluation
)
RetrievalRerankerArtifact = _retrieval_learning_artifacts_domain.RetrievalRerankerArtifact
RetrievalTrainingRun = _retrieval_learning_artifacts_domain.RetrievalTrainingRun
SearchFeedback = _retrieval_interactions_domain.SearchFeedback
SearchHarnessEvaluation = _retrieval_replay_governance_domain.SearchHarnessEvaluation
SearchHarnessEvaluationSource = _retrieval_replay_governance_domain.SearchHarnessEvaluationSource
SearchHarnessRelease = _retrieval_replay_governance_domain.SearchHarnessRelease
SearchHarnessReleaseReadinessAssessment = (
    _retrieval_replay_governance_domain.SearchHarnessReleaseReadinessAssessment
)
SearchReplayQuery = _retrieval_replay_governance_domain.SearchReplayQuery
SearchReplayRun = _retrieval_replay_governance_domain.SearchReplayRun
SearchRequestRecord = _retrieval_interactions_domain.SearchRequestRecord
SearchRequestResult = _retrieval_interactions_domain.SearchRequestResult
SearchRequestResultSpan = _retrieval_interactions_domain.SearchRequestResultSpan
SemanticAssertion = _semantic_memory_domain.SemanticAssertion
SemanticAssertionCategoryBinding = _semantic_memory_domain.SemanticAssertionCategoryBinding
SemanticAssertionEvidence = _semantic_memory_domain.SemanticAssertionEvidence
SemanticCategory = _semantic_memory_domain.SemanticCategory
SemanticConcept = _semantic_memory_domain.SemanticConcept
SemanticConceptCategoryBinding = _semantic_memory_domain.SemanticConceptCategoryBinding
SemanticConceptTerm = _semantic_memory_domain.SemanticConceptTerm
SemanticEntity = _semantic_memory_domain.SemanticEntity
SemanticFact = _semantic_memory_domain.SemanticFact
SemanticFactEvidence = _semantic_memory_domain.SemanticFactEvidence
SemanticGovernanceEvent = _semantic_memory_domain.SemanticGovernanceEvent
SemanticGraphSnapshot = _semantic_memory_domain.SemanticGraphSnapshot
SemanticOntologySnapshot = _semantic_memory_domain.SemanticOntologySnapshot
SemanticTerm = _semantic_memory_domain.SemanticTerm
TechnicalReportClaimRetrievalFeedback = (
    _audit_and_evidence_domain.TechnicalReportClaimRetrievalFeedback
)
TechnicalReportReleaseReadinessDbGate = (
    _audit_and_evidence_domain.TechnicalReportReleaseReadinessDbGate
)
WorkspaceSemanticGraphState = _semantic_memory_domain.WorkspaceSemanticGraphState
WorkspaceSemanticState = _semantic_memory_domain.WorkspaceSemanticState
